version: '3'

networks:
  huihui-mahjong:
    driver: bridge

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "${HUIHUI_POSTGRES_PORT}:${HUIHUI_POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${HUIHUI_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${HUIHUI_POSTGRES_PASSWORD}
      POSTGRES_DB: ${HUIHUI_POSTGRES_DB}
    volumes:
      - ../huihui-data/postgres:/var/lib/postgresql/data
    networks:
      - huihui-mahjong

  pgadmin:
    depends_on:
      - postgres
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${HUIHUI_PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${HUIHUI_PGADMIN_PASSWORD}
    ports:
      - "8081:80"
    networks:
      - huihui-mahjong
